[package]
name = "missioncenter"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gl-rs = { package = "gl", version = "0.14" }
gtk = { package = "gtk4", version = "0.6", features = ["gnome_44"] }
lazy_static = { version = "1.4" }
minidl = "0.1"
skia-safe = { version = "0", features = ["egl", "textlayout"] }
sysinfo = { version = "0.28" }

[dependencies.adw]
package = "libadwaita"
version = "0.3"
features = ["v1_2"]
