[package]
name = "missioncenter"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gl-rs = { package = "gl", version = "0.14" }
gtk = { version = "0.6", package = "gtk4" }
skia-safe = { version = "0", features = ["egl", "textlayout"] }
sysinfo = "0.28"

[dependencies.adw]
package = "libadwaita"
version = "0.3"
features = ["v1_2"]

[dependencies.plotters]
git = "https://github.com/plotters-rs/plotters"
rev = "acf5158"

[dependencies.plotters-backend]
git = "https://github.com/plotters-rs/plotters"
rev = "acf5158"
