[package]
name = "missioncenter_gpud"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[dependencies]
raw_sync = { version = "0.1" }
shared_memory = { version = "0.12" }

[profile.release]
opt-level = 3
lto = true
